name: CI

on:
  push:
    branches:
      - main
  pull_request:

env:
  NX_VERBOSE_LOGGING: true

jobs:
  main:
    name: Nx Cloud - Main Job
    uses: nrwl/ci/.github/workflows/nx-cloud-main.yml@v0.11.3
    with:
      main-branch-name: main
      number-of-agents: 3
      init-commands: |
        NX_VERBOSE_LOGGING=true npx nx-cloud start-ci-run --distribute-on="manual" --stop-agents-after="build"
      parallel-commands: |
        NX_VERBOSE_LOGGING=true npx nx-cloud record -- npx nx format:check
      parallel-commands-on-agents: |
        NX_VERBOSE_LOGGING=true npx nx affected --target=lint --parallel=3
        NX_VERBOSE_LOGGING=true npx nx affected --target=test --parallel=3 --ci --code-coverage
        NX_VERBOSE_LOGGING=true npx nx affected --target=build --parallel=3

  agents:
    name: Nx Cloud - Agents
    uses: nrwl/ci/.github/workflows/nx-cloud-agents.yml@v0.11.3
    with:
      number-of-agents: 3
